# Generated by Django 4.1.5 on 2023-02-12 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('comercial', models.CharField(max_length=60)),
                ('razon_social', models.CharField(max_length=60)),
                ('ruc', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('contabilidad', models.BooleanField()),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_permiso', models.CharField(max_length=30)),
                ('estado', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'permisos',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=200)),
                ('estado', models.IntegerField()),
                ('fecha', models.IntegerField()),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ci', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fcha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'trabajador',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('estado', models.IntegerField()),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_models.rol')),
                ('id_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_models.trabajador')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sucursal', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=200)),
                ('estado', models.IntegerField()),
                ('correo', models.CharField(max_length=200)),
                ('telefono', models.IntegerField()),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_models.empresa')),
            ],
            options={
                'db_table': 'sucursal',
            },
        ),
        migrations.CreateModel(
            name='Permisos_emision',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_permisos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_models.permisos')),
            ],
            options={
                'db_table': 'permisos_emision',
            },
        ),
        migrations.CreateModel(
            name='Historial_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_models.usuario')),
            ],
            options={
                'db_table': 'historial_login',
            },
        ),
    ]
